
# Project ID - Keep this line at the top!
project_id = "twznrtbvykvtumfapvsk"

[api]
# Port number for the API
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[functions]
[functions.initiate-call]
verify_jwt = false
